---
output: 
  flexdashboard::flex_dashboard:
    css: styles.css
    orientation: rows
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library("flexdashboard")
library("highcharter")
library("dplyr")
library("tidyr")
library("purrr")
library("readr")
library("ggplot2")

urldata <- "https://raw.githubusercontent.com/data-is-plural/nuclear-explosions/master/data/sipri-report-explosions.csv"
df <- read_csv(urldata)
df <- df %>% 
  mutate(date = as.Date(as.character(date_long), format = "%Y%m%d"),
         country  = sub("^(PAKIST|INDIA)$", "INDIA & PAKISTAN", country)) %>% 
  arrange(date) %>% 
  group_by(country) %>% 
  mutate(rn = row_number()) %>% 
  ungroup()
    
ggplot(df) + geom_line(aes(date, rn, color = country)) + scale_y_sqrt()
ggplot(df) + geom_point(aes(date, country, color = country), size = 3, alpha = 0.25)

thm <- hc_theme(
  chart = list(backgroundColor = "#2B2B2B"),
  colors = c("#E71409", "#337DBA", "#49B044", "#9B4BA7", "#A55B12", "#ACAD1F", "#302C2A")
  )
```

Row
-----------------------------------------------------------------------

###

```{r}
library("httr")
library("geojsonio")

world <- "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json" %>% 
  GET() %>% 
  content() %>% 
  jsonlite::fromJSON(simplifyVector = FALSE)

# world$features %>% purrr::map_chr(function(x) x$properties$name) %>% { which(. == "Antarctica")}
world$features[[7]] <- NULL

dfbooms <- df %>% 
  select(country, latitude, longitude, year, date, name) 

boomsjson <- geojson_json(dfbooms, lat = "latitude", lon = "longitude")

highchart(type = "map") %>% 
  hc_add_theme(thm) %>% 
  hc_plotOptions(
    series = list(
      showInLegend = FALSE
    )
  ) %>% 
  hc_add_series(mapData = world, nullColor = "#2b2b2b") %>% 
  hc_add_series(data = boomsjson, type = "mappoint", dataLabels = list(enabled = FALSE),
                name = "Airports", color = 'rgba(250, 250, 250, 0.7)',
                tooltip = list(pointFormat = "{point.properties.name}: {point.properties.date}"))


```

Row
-----------------------------------------------------------------------

### 

```{r}
hc <- highchart() %>% 
  hc_add_theme(thm) %>% 
  hc_legend(enabled = FALSE) %>%
  hc_yAxis(max = 1200) %>% 
  hc_plotOptions(
    series = list(animation = list(duration = 10*1000))
  )
for (c in unique(df$country)) {
  df2 <- df %>% filter(country == c)
  hc <- hc %>% hc_add_series_times_values(df2$date, df2$rn, name = c)
}
hc
```

###

```{r}
dfexp <- df %>%
  select(country, year) %>% 
  distinct() %>% 
  expand(country, year) %>% 
  left_join(
    df %>% 
      group_by(country, year) %>% 
      summarize(nb = n()) %>% 
      ungroup(),
    by = c("country", "year")
    ) %>% 
  mutate(nb = ifelse(is.na(nb), 0, nb)) %>% 
  arrange(country, year) %>% 
  group_by(country) %>%
  mutate(nbcum = cumsum(nb))

# dfexp %>% group_by(country) %>% summarise(nb = sum(nb)) %>% arrange(desc(nb))
# df %>% count(country) %>% arrange(desc(n))

ds <- dfexp %>% 
  group_by(country) %>% 
  do(seq = list(sequence = .$nbcum)) %>%
  ungroup() %>% 
  .$seq

orderls <- ds %>% map(function(x) tail(x[[1]], 1)) %>% 
  unlist() %>% 
  order(decreasing = TRUE)
  
ds <- ds[orderls]

df2 <- df %>% count(country) %>% arrange(desc(n))

highchart() %>% 
  hc_add_theme(thm) %>% 
  hc_chart(type = "column") %>% 
  hc_xAxis(categories = df2$country) %>% 
  hc_yAxis(max = 1200) %>% 
  hc_add_series(name = "B", data = ds, colorByPoint = TRUE,
                showInLegend = FALSE
                ) %>% 
  hc_motion(enabled = TRUE,
            updateInerval = 50,
            autoPlay = TRUE,
            labels = unique(dfexp$year))
# df2 <- df %>% count(country) %>% arrange(desc(n))
# hc <- highchart() %>%
#   hc_legend(enabled = FALSE) %>%
#   hc_chart(type = "column") %>%
#   hc_xAxis(categories = df2$country) %>%
#   hc_add_series_labels_values(df2$country, df2$n, colorByPoint = TRUE)
# hc
```
